[serial]
port = "/dev/ttyACM0"
baudrate = 9600
# Topics can be a single string or a comma‐separated list
topics = "rm2/wind/speed"

[mqtt]
hostname = "test.mosquitto.org"
topics = ["rm1/gps/lat", "rm1/gps/long"]

[aggregator]
interval = 1

[track]
checkpoint_interval = 30
max_checkpoint_files = 3
trim_fraction = 0.5
max_datapoints = 1e5

[saving]
# Default data-logging mode: 'continuous' or 'on-demand'
default_mode = "continuous"

[files]
# Please use '_fname' for files and '_dir' for directories
logger_fname = "default.log"
cdn_dir = "mothics/static"
output_dir = "data"

[webapp]
# Dashboard data refresh time in seconds 
data_refresh = 2
# Timeouts in seconds for remote unit status
timeout_offline = 60
timeout_noncomm = 30
# Remote unit names mapping
rm_thesaurus = {rm1 = "GPS+IMU", rm2 = "Anemometer"}
# CDNs to download
cdns = ["https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js", "https://cdn.bokeh.org/bokeh/release/bokeh-3.6.2.min.js", "https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.6.2.min.js", "https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.6.2.min.js"]