[gps]
    [gps.interface]
        name = "UART_GPS"
        port = "/dev/ttyS0"
        baudrate = 9600
        # Topics can be a single string or a comma‐separated list
        topics = "rm2/wind/speed"

# --- IMU BNO08x ---
[[i2c]]
    name = "bno08x"
    type = "bno08x"
    address = 0x4A
    bus = 1
    poll_interval = 0.05
    topics = [
        "rm3/imubno/accel_x", "rm3/imubno/accel_y", "rm3/imubno/accel_z",
        "rm3/imubno/gyro_x",  "rm3/imubno/gyro_y",  "rm3/imubno/gyro_z",
        "rm3/imubno/mag_x",   "rm3/imubno/mag_y",   "rm3/imubno/mag_z"
    ]

# # --- Barometro DPS310 ---
# [[i2c]]
# name = "dps310"
# type = "dps310"
# address = 0x77
# bus = 1
# poll_interval = 0.2
# topics = [
#     "rm3/env/pressure",
#     "rm3/env/temperature"
# ]

# # --- MPU6050 ---
# [[i2c]]
# name = "mpu6050"
# type = "mpu6050"
# address = 0x68
# bus = 1
# poll_interval = 0.05
# topics = [
#     "rm3/imu6/accel_x", "rm3/imu6/accel_y", "rm3/imu6/accel_z",
#     "rm3/imu6/gyro_x",  "rm3/imu6/gyro_y",  "rm3/imu6/gyro_z",
#     "rm3/imu6/temperature"
# ]


[communicator]
# Trim threshold for raw_data dict
max_values = 1e3
# Fraction of values to trim from raw_data 
trim_fraction = 0.5

# [unit_conversion]
# "rm3/wind/speed" = "rm3/wind/speed @ value * 1000"

# [imu_calibration.offsets]
# "rm1/imu/yaw"   = 0
# "rm1/imu/pitch" = 0
# "rm1/imu/roll"  = 0

[aggregator]
# Sampling interval in seconds
interval = 0.25

[track]
# Interval in seconds for checkpoint generation
checkpoint_interval = 120
# Maximum number of checkpoint files to keep in `data/chk/`
max_checkpoint_files = 3
# Fraction of values to trim from track
trim_fraction = 0.5
# Trim threshold for track
max_datapoints = 1e5

[database]
# Start database at startup
startup = false
# Validation of tracks using a premade schema
validation = false

[saving]
# Default data-logging mode: 'continuous' or 'on-demand'
default_mode = "on-demand"

[files]
# Please use '_fname' for files and '_dir' for directories
logger_fname = "default.log"
cdn_dir = "mothics/static"
# Data output directory
output_dir = "data"

[webapp]
identifier = 'BFL'
# Dashboard data refresh time in seconds 
data_refresh = 0.25
# Timeouts in seconds for remote unit status
timeout_offline = 60
timeout_noncomm = 30
# Remote unit names mapping
rm_thesaurus = {rm1 = "IMU", rm2 = "GPS", rm3 = 'Box hygrometer'}
# Data names mapping
data_thesaurus = {"rm1/imu/yaw" = 'Yaw', "rm1/imu/pitch" = 'Pitch', "rm1/imu/roll" = 'Roll', "rm2/gps/lat" = 'Latitude', "rm2/gps/long" = 'Longitude', "rm2/gps/altitude" = 'GPS altitude', "rm2/gps/sats" = 'Satellites', "rm2/gps/speed" = 'GPS speed', "rm2/gps/cog" = 'Course over ground', "rm2/gps/time" = 'GPS time', "rm2/gps/status" = 'GPS status', "rm1/imu/sample_rate" = 'IMU sampling rate', "rm2/gps/sample_rate" = 'GPS sampling rate', 'rm3/env/temp' = 'Box temperature', 'rm3/env/hum' = 'Box humidity'}
# Data to hide from cards
hidden_data_cards = ["rm2/gps/time", "rm1/imu/sample_rate", "rm2/gps/sample_rate"]
# Data to hide from plots
hidden_data_plots = ["rm2/gps/status", "rm2/gps/time"]
# CDNs to download
cdns = ["https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js", "https://cdn.bokeh.org/bokeh/release/bokeh-3.6.2.min.js", "https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.6.2.min.js", "https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.6.2.min.js", "https://unpkg.com/leaflet@1.9.4/dist/leaflet.js", "https://unpkg.com/leaflet@1.9.4/dist/leaflet.css", "https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css", "https://cdn.jsdelivr.net/npm/@yaireo/tagify", "https://cdn.plot.ly/plotly-3.0.1.min.js", "https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css", "https://cdn.jsdelivr.net/npm/@yaireo/tagify"]
#[webapp.gps]
# Map lat/long range for tiles download
#lat_range = [45.5, 45.8]
#lon_range = [13.5, 14.0]
# Zoom levels for tiles download
#zoom_levels = [13, 14, 15]
# Track coloring
track_variable = 'speed'
track_thresholds = [1, 5, 15]
track_colors = ["#3366cc", "#66cc66", "#ffcc00", "#cc3333"]
track_units = 'm/s'
# Track history length in minutes
track_history = 10

[cli]
# Shutdown button pin
button_pin = 21
# Commands to run at CLI startup
# startup_commands = []
