[serial]
port = "/dev/ttyACM0"
baudrate = 9600
# Topics can be a single string or a comma‐separated list
topics = "rm2/wind/speed"

[mqtt]
hostname = "test.mosquitto.org"
topics = ["rm1/gps/lat", "rm1/gps/long"]

[aggregator]
interval = 1
output_dir = "data"

[webapp]
logger_fname = "default.log"
track_manager_directory = "data/"
# Remote unit names mapping.
rm_thesaurus = {rm1 = "GPS+IMU", rm2 = "Anemometer"}
# CDNs to download
cdns = ["https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js", "https://cdn.bokeh.org/bokeh/release/bokeh-3.6.2.min.js", "https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.6.2.min.js", "https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.6.2.min.js"]
cdn_directory = "mothics/static"