
[gps]
    [gps.interface]
        name = "UART_GPS"
        port = "/dev/ttyS0"
        baudrate = 9600

[imu]
    name = "BNO055"
    port = "/dev/ttyAMA5"
    baudrate = 115200

[[gpio]]
	"type" = "dht22"
	"name" = "Temperature_and_humidity_sensor"
	"pin" = 6
	"topic_root" = "rm3/env/"
	"poll_interval" = 5.0

[communicator]
    # Trim threshold for raw_data dict
    max_values = 2e1
    # Fraction of values to trim from raw_data 
    trim_fraction = 0.5

[aggregator]
    # Sampling interval in seconds
    interval = 1

[track]
    # Interval in seconds for checkpoint generation
    checkpoint_interval = 30
    # Maximum number of checkpoint files to keep in `data/chk/`
    max_checkpoint_files = 3
    # Fraction of values to trim from track
    trim_fraction = 0.5
    # Trim threshold for track
    max_datapoints = 1e5

[saving]
    # Default data-logging mode: 'continuous' or 'on-demand'
    default_mode = "continuous"

[files]
    # Please use '_fname' for files and '_dir' for directories
    logger_fname = "default.log"
    cdn_dir = "mothics/static"
    # Data output directory
    output_dir = "data"

[webapp]
    # Dashboard data refresh time in seconds 
    data_refresh = 2
    # Timeouts in seconds for remote unit status
    timeout_offline = 60
    timeout_noncomm = 30
    # Remote unit names mapping
    rm_thesaurus = {rm1 = "GPS+IMU", rm2 = "Anemometer"}
    # Data names mapping
    data_thesaurus = {"rm1/imu/yaw" = 'Yaw', "rm1/imu/pitch" = 'Pitch', "rm1/imu/roll" = 'Roll', "rm2/gps/lat" = 'Latitude', "rm2/gps/lon" = 'Longitude', "rm2/gps/altitude" = 'GPS altitude', "rm2/gps/sats" = 'Satellites', "rm2/gps/speed" = 'GPS speed', "rm2/gps/cog" = 'Course over ground', "rm2/gps/time" = 'GPS time', "rm2/gps/status" = 'GPS status', "rm1/imu/sample_rate" = 'IMU sampling rate', "rm2/gps/sample_rate" = 'GPS sampling rate', 'rm3/env/temp' = 'Box temperature', 'rm3/env/hum' = 'Box humidity'}
    # Data to hide from cards
    hidden_data_cards = ["rm2/gps/time", "rm1/imu/sample_rate", "rm2/gps/sample_rate"]
    # Data to hide from plots
    hidden_data_plots = ["rm2/gps/status", "rm2/gps/time"]
    # CDNs to download
    cdns = ["https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css", "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js", "https://cdn.bokeh.org/bokeh/release/bokeh-3.6.2.min.js", "https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.6.2.min.js", "https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.6.2.min.js", "https://unpkg.com/leaflet@1.9.4/dist/leaflet.js", "https://unpkg.com/leaflet@1.9.4/dist/leaflet.css", "https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css", "https://cdn.jsdelivr.net/npm/@yaireo/tagify", "https://cdn.plot.ly/plotly-3.0.1.min.js", "https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css", "https://cdn.jsdelivr.net/npm/@yaireo/tagify"]
