# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - master
    # Alternative: only build for tags.
    # tags:
    #   - '*'

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'  # Change to match your project’s Python version

        - name: Install Dependencies
          run: |
            pip install -r requirements.txt
            pip install pdoc3

        - name: Generate API Documentation
          run: |
            mkdir -p docs
            pdoc --html mothics --output-dir docs --force

        - name: Upload Documentation Artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: docs/mothics  # Adjusted to point to the generated docs folder

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4