name: Deploy Documentation

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Change if needed

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pdoc3 sphinx sphinx-rtd-theme

      # Generate API Documentation with pdoc3
      - name: Generate API Documentation (pdoc3)
        run: |
          mkdir -p docs/mothics/api
          pdoc --html cli.py mothics --output-dir docs/mothics/api --force

      # Generate Documentation with Sphinx
      - name: Build Sphinx Documentation
        run: |
          cd docs  # Assuming 'docs' contains conf.py and index.rst
          make html
          mkdir -p mothics/docs
          mv _build/html/* mothics/docs/

      # Upload full documentation (pdoc3 + Sphinx) as artifact
      - name: Upload Documentation Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/mothics

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4