name: Sphinx Documentation

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ahmad88me/sphinx-docs-action@v0.7
        with:
          python-version: '3.10'
          git-username: 'AST'
          git-email: 'youremail@users.noreply.github.com'
          project-path: 'mothics'
          commit-message: 'Update docs'
          github-token: ${{ secrets.GITHUB_TOKEN }}
